[package]
name = "emoji"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.10"
futures = "0.3" # for our async / await blocks
tokio = { version = "1.12.0", features = ["full"] }